In [1]:
import pandas as pd
import numpy as np

apt_price = pd.read_csv(
    "./data/apt_price_2022.csv",
    encoding="cp949", #한글전용코드 지정
    skiprows=15, #15줄은 설명문
    thousands="," # 3자리구분코드 ","를 없애기
)
# UnicodeDecodeError : 유니코드파일이 아니라서 오류
# ParserError : csv형식이 일정치 않음

In [2]:
apt_price

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202109,2,220000,2,1987.0,언주로 3,NaN,-,-
1,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202112,4,215000,3,1987.0,언주로 3,NaN,중개거래,서울 강남구
2,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202204,12,220000,4,1987.0,언주로 3,NaN,중개거래,서울 강남구
3,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202204,21,220000,2,1987.0,언주로 3,NaN,중개거래,서울 강남구
4,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202205,27,216000,2,1987.0,언주로 3,NaN,중개거래,서울 강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16942,서울특별시 중랑구 중화동,450,450.0,0.0,한신아파트(103~109),59.76,202207,20,74000,3,1997.0,동일로 752,NaN,중개거래,서울 중랑구
16943,서울특별시 중랑구 중화동,450,450.0,0.0,한신아파트(103~109),84.03,202207,27,91500,12,1997.0,동일로 752,NaN,중개거래,서울 중랑구
16944,서울특별시 중랑구 중화동,274-51,274.0,51.0,한영(101),84.69,202111,4,50000,2,2003.0,동일로144길 74,NaN,중개거래,"서울 송파구, 서울 중랑구"
16945,서울특별시 중랑구 중화동,274-51,274.0,51.0,한영(101),84.69,202204,9,49900,7,2003.0,동일로144길 74,NaN,중개거래,서울 중랑구
16946,서울특별시 중랑구 중화동,11-7,11.0,7.0,현대휴앤미(102동),76.43,202204,23,53000,6,2007.0,봉화산로27가길 19,NaN,중개거래,서울 중랑구

In [7]:
type(apt_price)

pandas.core.frame.DataFrame

In [7]:
type(apt_price)

pandas.core.frame.DataFrame

In [8]:
apt_price.columns #열 이름

Index(['시군구', '번지', '본번', '부번', '단지명', '전용면적(㎡)', '계약년월', '계약일', '거래금액(만원)',
       '층', '건축년도', '도로명', '해제사유발생일', '거래유형', '중개사소재지'],
      dtype='object')

In [9]:
 apt_price.index # 행 번호

RangeIndex(start=0, stop=16947, step=1)

In [10]:
apt_price.values # 데이터 - 2d numpy

array([['서울특별시 강남구 개포동', '658-1', 658.0, ..., nan, '-', '-'],
       ['서울특별시 강남구 개포동', '658-1', 658.0, ..., nan, '중개거래', '서울 강남구'],
       ['서울특별시 강남구 개포동', '658-1', 658.0, ..., nan, '중개거래', '서울 강남구'],
       ...,
       ['서울특별시 중랑구 중화동', '274-51', 274.0, ..., nan, '중개거래',
        '서울 송파구, 서울 중랑구'],
       ['서울특별시 중랑구 중화동', '274-51', 274.0, ..., nan, '중개거래', '서울 중랑구'],
       ['서울특별시 중랑구 중화동', '11-7', 11.0, ..., nan, '중개거래', '서울 중랑구']],
      dtype=object)

In [11]:
type(apt_price.values)

numpy.ndarray

In [12]:
apt_price.values.shape

(16947, 15)

In [13]:
apt_price.size

254205

In [28]:
apt_price.values[0] #pd로 읽어올때 앞에서 thousands 옵션 안줬을 때 결과값

array(['서울특별시 강남구 개포동', '658-1', 658.0, 1.0, '개포6차우성아파트1동~8동', 79.97,
       202109, 2, '220,000', 2, 1987.0, '언주로 3', nan, '-', '-'],
      dtype=object)

In [31]:
apt_price.values[0] # thousands 옵션 줬을 떄 결과값

array(['서울특별시 강남구 개포동', '658-1', 658.0, 1.0, '개포6차우성아파트1동~8동', 79.97,
       202109, 2, 220000, 2, 1987.0, '언주로 3', nan, '-', '-'], dtype=object)

In [32]:
apt_price.values[-1]

array(['서울특별시 중랑구 중화동', '11-7', 11.0, 7.0, '현대휴앤미(102동)', 76.43, 202204,
       23, 53000, 6, 2007.0, '봉화산로27가길 19', nan, '중개거래', '서울 중랑구'],
      dtype=object)

In [34]:
type(apt_price.values[0])

numpy.ndarray

In [37]:
type(apt_price["시군구"])

pandas.core.series.Series

In [3]:
apt_price["시군구"][-1]
#리스트 아니고 시리즈라서 안돼~~! 
# list의 index와 다르게 -1 이런식으로 접근 노노~

KeyError: -1

In [39]:
apt_price["시군구"][0] #이건 가능~

'서울특별시 강남구 개포동'

In [4]:
# apt_price["단지명"] #아파트이름
money = apt_price["거래금액(만원)"]
money.index = apt_price["단지명"]
money

단지명
개포6차우성아파트1동~8동    220000
개포6차우성아파트1동~8동    215000
개포6차우성아파트1동~8동    220000
개포6차우성아파트1동~8동    220000
개포6차우성아파트1동~8동    216000
                   ...
한신아파트(103~109)     74000
한신아파트(103~109)     91500
한영(101)            50000
한영(101)            49900
현대휴앤미(102동)        53000
Name: 거래금액(만원), Length: 16947, dtype: int64

In [5]:
apt_price["해제사유발생일"][
    apt_price["해제사유발생일"].notna()
]

96       20220111.0
100      20220320.0
116      20211231.0
136      20220818.0
141      20211007.0
            ...
16788    20211111.0
16795    20220125.0
16847    20211206.0
16895    20211228.0
16931    20220607.0
Name: 해제사유발생일, Length: 665, dtype: float64

In [81]:
apt_price.columns

Index(['시군구', '번지', '본번', '부번', '단지명', '전용면적(㎡)', '계약년월', '계약일', '거래금액(만원)',
       '층', '건축년도', '도로명', '해제사유발생일', '거래유형', '중개사소재지'],
      dtype='object')

In [85]:
for c in list(apt_price.columns):
    print(c)

시군구
번지
본번
부번
단지명
전용면적(㎡)
계약년월
계약일
거래금액(만원)
층
건축년도
도로명
해제사유발생일
거래유형
중개사소재지

In [82]:
type(apt_price.columns)

pandas.core.indexes.base.Index

In [87]:
apt_price.T

,0,1,2,3,4,5,6,7,8,9,...,16937,16938,16939,16940,16941,16942,16943,16944,16945,16946
시군구,서울특별시 강남구 개포동,서울특별시 강남구 개포동,서울특별시 강남구 개포동,서울특별시 강남구 개포동,서울특별시 강남구 개포동,서울특별시 강남구 개포동,서울특별시 강남구 개포동,서울특별시 강남구 개포동,서울특별시 강남구 개포동,서울특별시 강남구 개포동,...,서울특별시 중랑구 중화동,서울특별시 중랑구 중화동,서울특별시 중랑구 중화동,서울특별시 중랑구 중화동,서울특별시 중랑구 중화동,서울특별시 중랑구 중화동,서울특별시 중랑구 중화동,서울특별시 중랑구 중화동,서울특별시 중랑구 중화동,서울특별시 중랑구 중화동
번지,658-1,658-1,658-1,658-1,658-1,1282,1282,1282,1282,1282,...,450,450,450,450,450,450,450,274-51,274-51,11-7
본번,658.0,658.0,658.0,658.0,658.0,1282.0,1282.0,1282.0,1282.0,1282.0,...,450.0,450.0,450.0,450.0,450.0,450.0,450.0,274.0,274.0,11.0
부번,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,51.0,51.0,7.0
단지명,개포6차우성아파트1동~8동,개포6차우성아파트1동~8동,개포6차우성아파트1동~8동,개포6차우성아파트1동~8동,개포6차우성아파트1동~8동,개포래미안포레스트,개포래미안포레스트,개포래미안포레스트,개포래미안포레스트,개포래미안포레스트,...,한신아파트(103~109),한신아파트(103~109),한신아파트(103~109),한신아파트(103~109),한신아파트(103~109),한신아파트(103~109),한신아파트(103~109),한영(101),한영(101),현대휴앤미(102동)
전용면적(㎡),79.97,79.97,79.97,79.97,79.97,96.91,84.86,74.66,59.92,84.83,...,50.37,50.37,50.37,59.76,59.76,59.76,84.03,84.69,84.69,76.43
계약년월,202109,202112,202204,202204,202205,202109,202109,202109,202109,202109,...,202109,202109,202110,202110,202203,202207,202207,202111,202204,202204
계약일,2,4,12,21,27,4,8,16,17,24,...,17,25,9,21,27,20,27,4,9,23
거래금액(만원),220000,215000,220000,220000,216000,310000,278000,253000,210000,297000,...,68500,64500,70000,83200,73000,74000,91500,50000,49900,53000
층,2,3,4,2,2,7,4,2,8,7,...,26,1,18,26,20,3,12,2,7,6
건축년도,1987.0,1987.0,1987.0,1987.0,1987.0,2020.0,2020.0,2020.0,2020.0,2020.0,...,1997.0,1997.0,1997.0,1997.0,1997.0,1997.0,1997.0,2003.0,2003.0,2007.0
도로명,언주로 3,언주로 3,언주로 3,언주로 3,언주로 3,개포로 264,개포로 264,개포로 264,개포로 264,개포로 264,...,동일로 752,동일로 752,동일로 752,동일로 752,동일로 752,동일로 752,동일로 752,동일로144길 74,동일로144길 74,봉화산로27가길 19
해제사유발생일,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
거래유형,-,중개거래,중개거래,중개거래,중개거래,-,-,-,-,-,...,-,-,-,-,중개거래,중개거래,중개거래,중개거래,중개거래,중개거래
중개사소재지,-,서울 강남구,서울 강남구,서울 강남구,서울 강남구,-,-,-,-,-,...,-,-,-,-,서울 중랑구,서울 중랑구,서울 중랑구,"서울 송파구, 서울 중랑구",서울 중랑구,서울 중랑구

In [92]:
display(apt_price[["시군구", "단지명"]])

                 시군구             단지명
0      서울특별시 강남구 개포동  개포6차우성아파트1동~8동
1      서울특별시 강남구 개포동  개포6차우성아파트1동~8동
2      서울특별시 강남구 개포동  개포6차우성아파트1동~8동
3      서울특별시 강남구 개포동  개포6차우성아파트1동~8동
4      서울특별시 강남구 개포동  개포6차우성아파트1동~8동
...              ...             ...
16942  서울특별시 중랑구 중화동  한신아파트(103~109)
16943  서울특별시 중랑구 중화동  한신아파트(103~109)
16944  서울특별시 중랑구 중화동         한영(101)
16945  서울특별시 중랑구 중화동         한영(101)
16946  서울특별시 중랑구 중화동     현대휴앤미(102동)

[16947 rows x 2 columns]

In [96]:
display(apt_price[ "시군구":"단지명" ])
# 안돼~ 오류남 슬라이싱 안됨

TypeError: cannot do slice indexing on RangeIndex with these indexers [시군구] of type str

In [97]:
display(apt_price[ [ "시군구" , "단지명" ] ])
#팬시인덱싱 됨

                 시군구             단지명
0      서울특별시 강남구 개포동  개포6차우성아파트1동~8동
1      서울특별시 강남구 개포동  개포6차우성아파트1동~8동
2      서울특별시 강남구 개포동  개포6차우성아파트1동~8동
3      서울특별시 강남구 개포동  개포6차우성아파트1동~8동
4      서울특별시 강남구 개포동  개포6차우성아파트1동~8동
...              ...             ...
16942  서울특별시 중랑구 중화동  한신아파트(103~109)
16943  서울특별시 중랑구 중화동  한신아파트(103~109)
16944  서울특별시 중랑구 중화동         한영(101)
16945  서울특별시 중랑구 중화동         한영(101)
16946  서울특별시 중랑구 중화동     현대휴앤미(102동)

[16947 rows x 2 columns]

In [119]:
apt_price.rename(columns={"전용면적(㎡)":"전용면적_m2", "거래금액(만원)":"거래금액_만원"}, inplace=True)
apt_price

,시군구,번지,본번,부번,단지명,전용면적_m2,계약년월,계약일,거래금액_만원,층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202109,2,220000,2,1987.0,언주로 3,NaN,-,-
1,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202112,4,215000,3,1987.0,언주로 3,NaN,중개거래,서울 강남구
2,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202204,12,220000,4,1987.0,언주로 3,NaN,중개거래,서울 강남구
3,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202204,21,220000,2,1987.0,언주로 3,NaN,중개거래,서울 강남구
4,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202205,27,216000,2,1987.0,언주로 3,NaN,중개거래,서울 강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16942,서울특별시 중랑구 중화동,450,450.0,0.0,한신아파트(103~109),59.76,202207,20,74000,3,1997.0,동일로 752,NaN,중개거래,서울 중랑구
16943,서울특별시 중랑구 중화동,450,450.0,0.0,한신아파트(103~109),84.03,202207,27,91500,12,1997.0,동일로 752,NaN,중개거래,서울 중랑구
16944,서울특별시 중랑구 중화동,274-51,274.0,51.0,한영(101),84.69,202111,4,50000,2,2003.0,동일로144길 74,NaN,중개거래,"서울 송파구, 서울 중랑구"
16945,서울특별시 중랑구 중화동,274-51,274.0,51.0,한영(101),84.69,202204,9,49900,7,2003.0,동일로144길 74,NaN,중개거래,서울 중랑구
16946,서울특별시 중랑구 중화동,11-7,11.0,7.0,현대휴앤미(102동),76.43,202204,23,53000,6,2007.0,봉화산로27가길 19,NaN,중개거래,서울 중랑구

In [153]:
apt_price.head()

,시군구,번지,본번,부번,단지명,전용면적_m2,계약년월,계약일,거래금액_만원,층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202109,2,220000,2,1987.0,언주로 3,NaN,-,-
1,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202112,4,215000,3,1987.0,언주로 3,NaN,중개거래,서울 강남구
2,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202204,12,220000,4,1987.0,언주로 3,NaN,중개거래,서울 강남구
3,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202204,21,220000,2,1987.0,언주로 3,NaN,중개거래,서울 강남구
4,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202205,27,216000,2,1987.0,언주로 3,NaN,중개거래,서울 강남구

In [156]:
apt_price["층"].unique()

array([ 2,  3,  4,  7,  8,  9,  5, 15, 13, 17,  6, 10, 11,  1, 26, 19, 29,
       16, 23, 28, 12, 22, 32, 31, 14, 24, 20, 25, 21, 18, 35, 30, 38, 46,
       27, 34, 60, 64, 39, 56, 45, 36, 47, 42, 40, 62, 52, 33, 63, 44, -1,
       58, 43, 37, 41], dtype=int64)

In [157]:
apt_price["층"].nunique() #55가지 종류의 층이 사용됐다

55

In [159]:
apt_price["층"].value_counts()

 5     1293
 4     1223
 6     1201
 3     1153
 7     1083
 8     1041
 2     1019
 9      992
 11     952
 12     878
 10     874
 13     790
 1      774
 14     686
 15     609
 16     399
 17     370
 18     293
 19     242
 20     225
 21     150
 22     138
 23      98
 24      92
 25      54
 26      48
 27      45
 28      33
 29      29
 30      22
 32      18
 31      15
 34      14
 33      14
 35      11
-1       10
 39      10
 36      10
 38       6
 42       6
 45       5
 40       4
 41       3
 46       2
 43       2
 37       2
 56       1
 47       1
 64       1
 62       1
 52       1
 60       1
 63       1
 44       1
 58       1
Name: 층, dtype: int64

In [166]:
# 거래된 64층 아파트 정보 행 추출
apt_price[ apt_price['층'] == 64 ]

,시군구,번지,본번,부번,단지명,전용면적_m2,계약년월,계약일,거래금액_만원,층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
440,서울특별시 강남구 도곡동,467,467.0,0.0,타워팰리스1,222.48,202109,30,482500,64,2002.0,언주로30길 56,NaN,-,-

In [167]:
apt_price[ apt_price['층'] > 50 ]

,시군구,번지,본번,부번,단지명,전용면적_m2,계약년월,계약일,거래금액_만원,층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
439,서울특별시 강남구 도곡동,467,467.0,0.0,타워팰리스1,137.240,202109,2,368000,60,2002.0,언주로30길 56,NaN,-,-
440,서울특별시 강남구 도곡동,467,467.0,0.0,타워팰리스1,222.480,202109,30,482500,64,2002.0,언주로30길 56,NaN,-,-
447,서울특별시 강남구 도곡동,467,467.0,0.0,타워팰리스1,301.470,202205,12,870000,56,2002.0,언주로30길 56,NaN,중개거래,서울 강남구
471,서울특별시 강남구 도곡동,467-29,467.0,29.0,타워팰리스3,185.622,202111,23,423000,62,2004.0,언주로30길 26,NaN,중개거래,서울 강남구
474,서울특별시 강남구 도곡동,467-29,467.0,29.0,타워팰리스3,124.641,202202,10,300000,52,2004.0,언주로30길 26,NaN,중개거래,서울 강남구
476,서울특별시 강남구 도곡동,467-29,467.0,29.0,타워팰리스3,244.224,202203,30,554000,63,2004.0,언주로30길 26,NaN,중개거래,서울 강남구
3848,서울특별시 광진구 자양동,227-7,227.0,7.0,더샵스타시티,127.950,202204,22,198000,58,2007.0,아차산로 262,NaN,중개거래,경기 남양주시

In [171]:
sum(apt_price["건축년도"].isna())

2

In [172]:
# 건축년도가 결측치인 거래행 추출
apt_price[apt_price["건축년도"].isna()]

,시군구,번지,본번,부번,단지명,전용면적_m2,계약년월,계약일,거래금액_만원,층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
15276,서울특별시 은평구 수색동,30,30.0,0.0,DMCSKVIEW,84.99,202201,28,140000,7,NaN,수색로 216,NaN,중개거래,서울 은평구
15277,서울특별시 은평구 수색동,30,30.0,0.0,DMCSKVIEW,84.99,202202,10,137000,6,NaN,수색로 216,NaN,중개거래,서울 은평구

In [174]:
apt_price[ apt_price["단지명"] == "DMCSKVIEW"]

,시군구,번지,본번,부번,단지명,전용면적_m2,계약년월,계약일,거래금액_만원,층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
15276,서울특별시 은평구 수색동,30,30.0,0.0,DMCSKVIEW,84.99,202201,28,140000,7,NaN,수색로 216,NaN,중개거래,서울 은평구
15277,서울특별시 은평구 수색동,30,30.0,0.0,DMCSKVIEW,84.99,202202,10,137000,6,NaN,수색로 216,NaN,중개거래,서울 은평구

In [176]:
apt_price[ apt_price["도로명"] == '수색로 216']

,시군구,번지,본번,부번,단지명,전용면적_m2,계약년월,계약일,거래금액_만원,층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
15276,서울특별시 은평구 수색동,30,30.0,0.0,DMCSKVIEW,84.99,202201,28,140000,7,NaN,수색로 216,NaN,중개거래,서울 은평구
15277,서울특별시 은평구 수색동,30,30.0,0.0,DMCSKVIEW,84.99,202202,10,137000,6,NaN,수색로 216,NaN,중개거래,서울 은평구

In [7]:
# 건축년도가 정상인 행 추출
건축년도정상 = apt_price[ apt_price["건축년도"].notna() ]
apt_price["건축년도"] = 건축년도정상['건축년도'].astype("int32")

In [8]:
apt_price.head()

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202109,2,220000,2,1987.0,언주로 3,NaN,-,-
1,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202112,4,215000,3,1987.0,언주로 3,NaN,중개거래,서울 강남구
2,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202204,12,220000,4,1987.0,언주로 3,NaN,중개거래,서울 강남구
3,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202204,21,220000,2,1987.0,언주로 3,NaN,중개거래,서울 강남구
4,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202205,27,216000,2,1987.0,언주로 3,NaN,중개거래,서울 강남구

In [10]:
 apt_price.sort_index().head(3)
# sort_index()는 오름차순이 기본

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202109,2,220000,2,1987.0,언주로 3,NaN,-,-
1,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202112,4,215000,3,1987.0,언주로 3,NaN,중개거래,서울 강남구
2,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202204,12,220000,4,1987.0,언주로 3,NaN,중개거래,서울 강남구

In [11]:
apt_price.sort_index(ascending=False).head(3) #ascending=false 주면 내림차순

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
16946,서울특별시 중랑구 중화동,11-7,11.0,7.0,현대휴앤미(102동),76.43,202204,23,53000,6,2007.0,봉화산로27가길 19,NaN,중개거래,서울 중랑구
16945,서울특별시 중랑구 중화동,274-51,274.0,51.0,한영(101),84.69,202204,9,49900,7,2003.0,동일로144길 74,NaN,중개거래,서울 중랑구
16944,서울특별시 중랑구 중화동,274-51,274.0,51.0,한영(101),84.69,202111,4,50000,2,2003.0,동일로144길 74,NaN,중개거래,"서울 송파구, 서울 중랑구"

In [188]:
apt_price.sort_values(by=["층","거래금액_만원"], ascending=[True,False])

,시군구,번지,본번,부번,단지명,전용면적_m2,계약년월,계약일,거래금액_만원,층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
15714,서울특별시 은평구 진관동,84,84.0,0.0,은평뉴타운우물골(두산위브7단지),134.750,202111,2,148000,-1,2010.0,진관2로 57-37,NaN,중개거래,"서울 강서구, 서울 은평구"
14709,서울특별시 용산구 이촌동,193-3,193.0,3.0,강변,66.080,202109,15,103000,-1,1971.0,이촌로 104,NaN,-,-
16924,서울특별시 중랑구 중화동,331-64,331.0,64.0,연합파크빌,80.010,202109,7,76500,-1,2003.0,봉화산로1길 16,NaN,-,-
3029,서울특별시 관악구 남현동,1081-4,1081.0,4.0,우평,99.290,202204,5,70000,-1,2003.0,남부순환로262길 37,NaN,중개거래,서울 관악구
3030,서울특별시 관악구 남현동,1081-4,1081.0,4.0,우평,99.290,202204,5,70000,-1,2003.0,남부순환로262길 37,20220602.0,중개거래,서울 관악구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3848,서울특별시 광진구 자양동,227-7,227.0,7.0,더샵스타시티,127.950,202204,22,198000,58,2007.0,아차산로 262,NaN,중개거래,경기 남양주시
439,서울특별시 강남구 도곡동,467,467.0,0.0,타워팰리스1,137.240,202109,2,368000,60,2002.0,언주로30길 56,NaN,-,-
471,서울특별시 강남구 도곡동,467-29,467.0,29.0,타워팰리스3,185.622,202111,23,423000,62,2004.0,언주로30길 26,NaN,중개거래,서울 강남구
476,서울특별시 강남구 도곡동,467-29,467.0,29.0,타워팰리스3,244.224,202203,30,554000,63,2004.0,언주로30길 26,NaN,중개거래,서울 강남구
440,서울특별시 강남구 도곡동,467,467.0,0.0,타워팰리스1,222.480,202109,30,482500,64,2002.0,언주로30길 56,NaN,-,-